### ISSUE TITLE
0.96.0b0  Platform not found: climate.e_thermostaat

### ISSUE THREAD

**Issue by remb0** [custom-components/climate.e_thermostaat#3]
Today I updated to 0.96.0b0  and I got the message: 
Platform not found: climate.e_thermostaat

in logs I see:
Platform not found: climate.e_thermostaat
18:20 components/hassio/__init__.py (ERROR)

what can I do to deliver more debugging info?  I'm running hassio 0.96.0b0 in a docker @ intel NUC.

--
can you also add this lovely component to HACS?

**Comment by gerard33** [comment]
Details here -> https://community.home-assistant.io/t/e-thermostaat-icy/493/70

**Comment by gerard33** [comment]
Version 0.3.0 released with support for HA 0.96.
Also HACS is supported now and will show the correct version based on your HA version.

**Comment by remb0** [comment]
this is great!!!   thank for your hard work.
