### ISSUE TITLE
0.4.1 Released?

### ISSUE THREAD

**Issue by ludeeus** [custom-components/climate.e_thermostaat#9]
0.4.1 of this integration was recently released <https://github.com/custom-components/climate.e_thermostaat/releases/tag/0.4.1>
But the manifest still say 0.4.0 <https://github.com/custom-components/climate.e_thermostaat/blob/0.4.1/custom_components/e_thermostaat/manifest.json#L4>

This will probably not be the last time that happens, I suggest injecting the version on release like this:
<https://github.com/custom-components/combined/blob/master/.github/workflows/release.yml> that way the release tag and the manifest will always be in sync.
And this <https://github.com/custom-components/combined/blob/master/hacs.json#L3-L4> to make changes needed for HACS.
With this approach, I personally like to set the version in the manifest.json file to "0.0.0" to signal it's a development version.

Feel free to close this or ping me for review if this get's implemented.

**Comment by gerard33** [comment]
Oopsie 🙈
I guess I need some coffee as well 😉

I have implemented the changes you suggested in #10, #11 and #12. Can you have a look if I did it the right way?

**Comment by ludeeus** [comment]
Why 3 different PR's? :sweat_smile:

**Comment by gerard33** [comment]
Yeah, I would call it laziness. I am making the changes from the Github UI and am not aware of combing it in 1 PR from the UI 😉

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/120890233-8b580300-c601-11eb-84d5-58693b6fd205.png)
Select the branch you want to add more changes to

**Comment by gerard33** [comment]
Ah, could have thought of that myself. Will use that a next time 🧑‍🎓
